[package]
name = "goxoy_p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
md5 = "0.7.0"
colored = "2.1.0"
serde_derive = "1.0.158"
serde = { version = "1.0.158", features = ["derive"] }

